name: Playwright Tests
on:
  push:
    branches: [main]
jobs:
  js-playwrith-project:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-focal
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Tests
        run: |
          echo "Start the shoping store appication"
          ./shopping-store-linux-amd64 &
          echo "Install dependencies from lockfile"
          npm ci
          echo "Run playwright test"
          npm run test:ci

      - name: Upload test results artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ inputs.testsCategory }}-${{ matrix.os }}
          retention-days: 1
          path: |
            ./testResults
